### PR TITLE
New character models for needed for MT after #6007

### PR DESCRIPTION
**Pull request by lhofhansl**
Fixed character models for MT after [#6007](https://github.com/minetest/minetest/pull/6007)

### CODE REVIEW

**Comment by stujones11** [comment]
Thanks, though I have already made alternative models available for those that wish to continue using development builds https://forum.minetest.net/viewtopic.php?f=11&t=4654&start=650#p284858

I will probably add a feature branch once settable player collision boxes are fully integrated into MTG with any changes to the player model that are currently being proposed https://github.com/minetest/minetest_game/pull/1411

**Comment by Wuzzy2** [comment]
Keep in mind that if you merge this, you will break compability with 0.4.16. I would wait with merging this until Minetest 0.5.0 is released.

**Comment by stujones11** [comment]
> Keep in mind that if you merge this, you will break compability with 0.4.16

This is why I intend to merge this into a feature branch instead. For you can now simply substitute 3d_armor_character.b3d with the updated version.

**Comment by lhofhansl** [comment]
I left the default model at v2. So merging this _should_ be fine. Not saying it should be merged, just that it's OK :)

**Comment by lhofhansl** [comment]
Feel free to close this one then.

**Comment by stujones11** [comment]
> Feel free to close this one then.

No need, I am sure your changes are fine and I can eventually merge them to a new branch. In the meantime your fork provides an alternative upgrade path for others.

**Comment by lhofhansl** [comment]
I think you might want to take your updated models. I can update this PR accordingly.

**Comment by stujones11** [comment]
Okay, there was a problem with the models not being exported correctly anyway, not sure about yours but the latest version has been tested with advanced lighting.

**Pull request closed without merging**
