### PR TITLE
Add "ban" privilege for kill chatcommand

### PR DESCRIPTION
**Pull request by paly2**
Only the admin should be able to execute the "kill" chatcommand

### CODE REVIEW

**Comment by stujones11** [comment]
Why should this feature be restricted to admin when It only allows players to kill themselves?
I must admit that I did not add this feature myself. It was contributed by @tenplus1 #45 so I am not really sure why hp is set to -1001 but guess that there must have been a reason.

**Comment by paly2** [comment]
It only allows players to kill themselves, but that is quite inconsistent: the command takes one paramater, the name of the player who is killed. That is fixed by the second commit of this pull request.

Maybe creating another command (/suicide) which doesn't take any paramater and doesn't require any privilege would be better ? /kill (as modified by this pull request) is a useful tool for admins...

I can't understand too why hp is set to -1001 :confused:

**Comment by mgl512** [comment]
The help on this chat command is quite misleading.
Written:
`/kill <name> : Kills player instantly`
Meant:
`/kill <name> : commit a suicide and totally ignore <name>.`

There's no reason to set the hp below 0: the C++ core changes anything below 0 to 0 and anything above PLAYER_MAX _HP (hardcoded to 20) to PLAYER_MAX_HP. Maybe tenplus1 intended to apply 1001 points of damage. But set_hp doesn't apply damage, it really sets the value of your health bar. 0 means death.

**Comment by stujones11** [comment]
While I agree that this command was not very well named, I do think the idea of having to confirm your own name was a good one. I am hoping @tenplus1 might comment on this.

**Comment by BrunoMine** [comment]
I'm trying to understand what the relationship between this command and armor.

**Comment by stujones11** [comment]
> I'm trying to understand what the relationship between this command and armor.

I agree, I am not sure that this mod is the right place for either of those command but I will merge if a /suicide command is included with the same functionality as the existing /kill command.

**Comment by mgl512** [comment]
> I will merge if a /suicide command is included with the same functionality as the existing /kill command.

The existing /kill command *is* a suicide command. A *very misleading* one that lets you think you can kill someone else. Hence the "ban" priv that paly2 wanted to associate to it. It doesn't even care for its parameter. Whatever it is, it will kill *you*. Try "/kill bill" and see. 

At least remove its parameter and call it /suicide if you don't want to merge the pull request. Or remove it completely, Where is the need for a suicide command in an armor mod ? Can you be so trapped in an (admin) armor that you have to die to go on ?

**Comment by stujones11** [comment]
> The existing /kill command is a suicide command.

I agree this is misleading, if @paly2 makes either of the changes you suggest then I can merge. Otherwise I will fix this myself after I release version 0.5.0.

**Comment by paly2** [comment]
I guess the /kill chatcommand (killing another player) may be useful, even if it has no much relationship with an amor mod (except to kill a player who has an admin admor). But a /suicide command is totally useless, in my opinion, removing it totally is better than renaming the /kill command (but less good than changing the /kill command to make it killing another player).

**Comment by stujones11** [comment]
You make some good points and would I agree the /kill command makes much more sense like that. I would have merged this ages ago had it not been for the fact that the command was added by another contributor who clearly thought the 'suicide' feature was useful. I tend to trust his word since he runs one of the most popular and respected public servers.

I will add a /suicide command myself to replace the current functionality then I will merge this as-is.

**Pull request merged**
