### PR TITLE
Fix crash with UI but no technic

### PR DESCRIPTION
**Pull request by numberZero**
https://github.com/minetest-mods/unified_inventory/issues/111
Should help.

### CODE REVIEW

**Comment by stujones11** [comment]
Thanks for the PR but I don't understand what is wrong with the current code. `minetest.global_exists` shouldn't cause a crash unless something else is wrongly declaring it? However, I will merge since using a local variable based on the actual mod's existence is a better solution anyway :)

**Comment by numberZero** [comment]
“Should help” means “Didn’t test, but will work probably.” I just found out that it uses different methods (`global_exists` in one place but `get_modpath` in another) of detecting `technic` in different places, and unified them. @expertmm Does this help actually?

On locals: each file (called via `dofile`) has its own scope. Indeed, it behaves just like a function, it can even return values (and probably handle arguments as well, don’t remember).

**Comment by numberZero** [comment]
Tested. It works.
With `technic_worldgen` but no `technic`, c812e0a crashes but 579d245 doesn’t.

**Comment by stujones11** [comment]
Thanks again, I never really doubted you :)

**Pull request merged**
