### PR TITLE
Add ability to breath underwater

### PR DESCRIPTION
**Pull request by tenplus1**
Added functionality for armor to have armor_water=1 in groups so that player can breathe underwater.

### CODE REVIEW

**Comment by stujones11** [comment]
Nice, and I see you fixed a potential bug there too, cheers!

**Comment by tenplus1** [comment]
It checks every 1 second so thankfully wont lag players or servers.

**Comment by 0-afflatus** [comment]
It would be great to generalise this sort of thing, so we can add arbitrary 'magic' powers. I'd like to create a variety of wearable items with powers, is this within scope for 3d_armor?

**Comment by stujones11** [comment]
>It checks every 1 second so thankfully wont lag players or servers.
I will take your word on that since you run a very popular server, I guess you know better than most

>It would be great to generalise this sort of thing, so we can add arbitrary 'magic' powers. I'd like to create a variety of wearable items with powers, is this within scope for 3d_armor?
Sure, there is quite a lot you can do with it and this feature extends those possibilities even further,
irrc, someone already made a spacesuit.

**Pull request merged**
