### PR TITLE
new armorstand mapping

### PR DESCRIPTION
**Pull request by tobyplowy**
You can customize this however you want every face on the model has a Unique texture on the mapping
Also the mapping is nicely organised and it uses the same sorting as Minecraft textures

This is what's possible
cddddddd
The texture for the above picture
armor_stand

 also with my mapping you can do this 
hd
i dunno why you wuld wanne do this but its possible XD

### CODE REVIEW

**Comment by stujones11** [comment]
It is important for package maintainers that you include an appropriate license for your texture. Please use the same format as the other sub-mods (like shields) with years included. I can change things on merge if that is a problem for you, just let me know which license you would prefer.

**Comment by tobyplowy** [comment]
@stujones11 eehhh I dount really understand

Can you edit the license just give credit to me for the new model mapping (the texture is based on defoult wood and steel so I dount need credit for that)

**Comment by stujones11** [comment]
> eehhh I dount really understand

Sorry if it seems like I'm being picky here but I really do now have to take care with licensing since the mod is now being packaged for Debian. #75

Since you based your work on the default textures then the following should apply.

> ShareAlike — If you remix, transform, or build upon the material, you must distribute
> your contributions under the same license as the original.

Therefore I will use Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0) if that is okay with you.

**Comment by tobyplowy** [comment]
I dunno wat that means but yes I guss

**Comment by stujones11** [comment]
Overall, the concept is good and I am happy to merge this as soon as I am able to make the necessary changes and test. I will try to get round to that as soon as possible but I would like to give other contributors and users a chance to comment on the proposed changes in the meantime.

**Comment by tobyplowy** [comment]
> I would like to give other contributors and users a chance to comment on the proposed changes in the meantime.

How would they know this exists?

**Comment by MT-Modder** [comment]
@tobyplowy Anyone who is "serious" about this mod will follow this repo and therefor notice this PR. You could take screenshots of the differences so people don't have to download your changes and test them themselves.

**Comment by tobyplowy** [comment]
@MT-Modder done

**Comment by tobyplowy** [comment]
@numberZero is this good? 
fuuuuuuuuuuuu stand
armor_stand

**Comment by MT-Modder** [comment]
Looks good 👍

**Comment by stujones11** [comment]
I've had to make a few changes due to resolution mismatches, however, the mapping mostly unchanged.

**Pull request closed without merging**
