### PR TITLE
add radiation resistance to technic armor

### PR DESCRIPTION
**Pull request by HybridDog**
https://github.com/stujones11/minetest-3d_armor/pull/34/files?w=1

the lead armor doesn't have textures and it only could work with https://github.com/minetest-technic/technic/pull/243

### CODE REVIEW

**Comment by stujones11** [comment]
That's a great idea, it makes the technic armor much more useful, although I'd rather try to avoid the hard dependency if possible. Also, will you be adding the textures at some stage or would you rather I did that?

**Comment by HybridDog** [comment]
>I'd rather try to avoid the hard dependency if possible.

without hard dependency the mod including its textures becomes loaded even if it does nothing

>Also, will you be adding the textures at some stage or would you rather I did that?

ldk how a lead armor looks like, so…

**Comment by stujones11** [comment]
> without hard dependency the mod including its textures becomes loaded even if it does nothing

That's fair comment, I just did not want everyone to think that technic is a requirement for the rest of the modpack but what you are saying makes sense I guess.

> ldk how a lead armor looks like, so l think l don't make them.

Me neither and textures aren't really my strong point but I'll see what I can come up with.

**Comment by stujones11** [comment]
I have added the textures and pushed this to a new branch if you would like to try it.

https://github.com/stujones11/minetest-3d_armor/commits/HybridDog-lead_armor

**Comment by HybridDog** [comment]
l like them, but l didn't try them.

**Comment by stujones11** [comment]
Glad you like them, it took me most of the afternoon to make them. I guess we now just have to wait for your technic PR to be accepted 8)

**Comment by stujones11** [comment]
One more thing, it would be nice if it could work with the current version of technic, if only as decoration.
It could perhaps offer some fire protection (it enabled) so not completely redundant. This would also mead I could merge this right away.

**Comment by HybridDog** [comment]
>it would be nice if it could also work with the current and older versions of technic

l haven't tested it but it should work.

**Comment by stujones11** [comment]
I have made some slight improvements to some textures and pushed them to the temp branch.

https://github.com/stujones11/minetest-3d_armor/tree/HybridDog-lead_armor

Also I decided it would be best to wait for https://github.com/minetest-technic/technic/pull/243 to be merged before adding this. Any idea what the hold-up is?

**Comment by HybridDog** [comment]
>I have made some slight improvements to some textures and pushed them to the temp branch.

l cherry-picked it

**Pull request closed without merging**
