### PR TITLE
added cactus armor and admin armor

### PR DESCRIPTION
**Pull request by crazyginger72**
admin armor has the option of being enabled vie the .conf with enable_admin_armor = true
also have enhanced wood and cactus shields!

### CODE REVIEW

**Comment by stujones11** [comment]
@crazyginger72 Thank you for your contribution, for the most part I like it and would be glad to merge the cactus and admin armor. There would, however, need to be some changes in configuration to keep it consistent with other armor configs using armor.conf

Also I do not think the swords are a necessary inclusion since there are other mods that add very similar items and this is really meant to be an armor mod, not a weapons mod.

If you are unable (or unwilling) to make the required changes to this PR then I will do so myself when I have time to test everything.

**Comment by crazyginger72** [comment]
I have removed the swords but am not 100% sure what you mean about the .conf

**Comment by stujones11** [comment]
@crazyginger72 Don't worry about it, just make the admin armor available to all but without crafts.
I will make it optional at a later date if there is a demand for that.

**Comment by crazyginger72** [comment]
ok i think this is what you want :)

**Comment by stujones11** [comment]
I have merged your request but had to make a few changes here and there, hope you don't mind.

Cheers!

**Comment by crazyginger72** [comment]
Thanks, i have had that on my servers for a while but deezl wanted it for his carbone so i decided to merge it :)

**Pull request closed without merging**
