### PR TITLE
Optimize textures using OptiPNG

### PR DESCRIPTION
**Pull request by Calinou**
This pull request decreases the file size of most textures by 40-50 %.

When editing the textures with GIMP, be sure to change the Image color mode.

### CODE REVIEW

**Comment by stujones11** [comment]
>When editing the textures with GIMP, be sure to change the Image color mode.

What mode should I be using?

Anyway, thanks for sharing the optimizatations,

**Comment by Calinou** [comment]
> What mode should I be using?

Image ⇒ Mode ⇒ RGB

**Comment by stujones11** [comment]
Thanks, I'll keep that in mind.

**Comment by ExeterDad** [comment]
Servers are going to love the difference of the last week.
@stujones11 any idea how much has change in total in the size of the mod now?

**Comment by stujones11** [comment]
I've known for a log time that b3d format would save a good bit on the model, I just wasn't able to get it to work. I am sure your png optimizations have saved a significant amount too, do you have the figures? I would be very interested to know.

**Comment by Calinou** [comment]
```
 3d_armor/textures/3d_armor_boots_admin.png           | Bin 612 -> 291 bytes
 3d_armor/textures/3d_armor_boots_admin_preview.png   | Bin 2059 -> 1413 bytes
 3d_armor/textures/3d_armor_boots_bronze.png          | Bin 632 -> 321 bytes
 3d_armor/textures/3d_armor_boots_bronze_preview.png  | Bin 2053 -> 1446 bytes
 3d_armor/textures/3d_armor_boots_cactus.png          | Bin 474 -> 308 bytes
 3d_armor/textures/3d_armor_boots_cactus_preview.png  | Bin 2014 -> 1413 bytes
 3d_armor/textures/3d_armor_boots_diamond.png         | Bin 629 -> 295 bytes
 3d_armor/textures/3d_armor_boots_diamond_preview.png | Bin 2051 -> 1460 bytes
 3d_armor/textures/3d_armor_boots_gold.png            | Bin 567 -> 287 bytes
 3d_armor/textures/3d_armor_boots_gold_preview.png    | Bin 2049 -> 1413 bytes
 3d_armor/textures/3d_armor_boots_mithril.png         | Bin 472 -> 216 bytes
 3d_armor/textures/3d_armor_boots_mithril_preview.png | Bin 1997 -> 1387 bytes
 3d_armor/textures/3d_armor_boots_steel.png           | Bin 609 -> 316 bytes
 3d_armor/textures/3d_armor_boots_steel_preview.png   | Bin 2040 -> 1460 bytes
 3d_armor/textures/3d_armor_boots_wood.png            | Bin 565 -> 274 bytes
 3d_armor/textures/3d_armor_boots_wood_preview.png    | Bin 2034 -> 1424 bytes
 3d_armor/textures/3d_armor_chestplate_admin.png      | Bin 1301 -> 782 bytes
 .../textures/3d_armor_chestplate_admin_preview.png   | Bin 1718 -> 1269 bytes
 3d_armor/textures/3d_armor_chestplate_bronze.png     | Bin 1404 -> 556 bytes
 .../textures/3d_armor_chestplate_bronze_preview.png  | Bin 1729 -> 1296 bytes
 3d_armor/textures/3d_armor_chestplate_cactus.png     | Bin 1221 -> 712 bytes
 .../textures/3d_armor_chestplate_cactus_preview.png  | Bin 1722 -> 1269 bytes
 3d_armor/textures/3d_armor_chestplate_diamond.png    | Bin 1287 -> 475 bytes
 .../textures/3d_armor_chestplate_diamond_preview.png | Bin 1654 -> 1221 bytes
 3d_armor/textures/3d_armor_chestplate_gold.png       | Bin 1120 -> 430 bytes
 .../textures/3d_armor_chestplate_gold_preview.png    | Bin 1664 -> 1187 bytes
 3d_armor/textures/3d_armor_chestplate_mithril.png    | Bin 1356 -> 669 bytes
 .../textures/3d_armor_chestplate_mithril_preview.png | Bin 1664 -> 1425 bytes
 3d_armor/textures/3d_armor_chestplate_steel.png      | Bin 1264 -> 537 bytes
 .../textures/3d_armor_chestplate_steel_preview.png   | Bin 1636 -> 1296 bytes
 3d_armor/textures/3d_armor_chestplate_wood.png       | Bin 1200 -> 453 bytes
 .../textures/3d_armor_chestplate_wood_preview.png    | Bin 1612 -> 1192 bytes
 3d_armor/textures/3d_armor_helmet_admin.png          | Bin 1164 -> 725 bytes
 3d_armor/textures/3d_armor_helmet_admin_preview.png  | Bin 1235 -> 883 bytes
 3d_armor/textures/3d_armor_helmet_bronze.png         | Bin 933 -> 602 bytes
 3d_armor/textures/3d_armor_helmet_bronze_preview.png | Bin 1182 -> 891 bytes
 3d_armor/textures/3d_armor_helmet_cactus.png         | Bin 846 -> 545 bytes
 3d_armor/textures/3d_armor_helmet_cactus_preview.png | Bin 1192 -> 883 bytes
 3d_armor/textures/3d_armor_helmet_diamond.png        | Bin 878 -> 524 bytes
 .../textures/3d_armor_helmet_diamond_preview.png     | Bin 1147 -> 902 bytes
 3d_armor/textures/3d_armor_helmet_gold.png           | Bin 830 -> 489 bytes
 3d_armor/textures/3d_armor_helmet_gold_preview.png   | Bin 1240 -> 893 bytes
 3d_armor/textures/3d_armor_helmet_mithril.png        | Bin 1159 -> 798 bytes
 .../textures/3d_armor_helmet_mithril_preview.png     | Bin 1144 -> 853 bytes
 3d_armor/textures/3d_armor_helmet_steel.png          | Bin 858 -> 556 bytes
 3d_armor/textures/3d_armor_helmet_steel_preview.png  | Bin 1161 -> 887 bytes
 3d_armor/textures/3d_armor_helmet_wood.png           | Bin 863 -> 485 bytes
 3d_armor/textures/3d_armor_helmet_wood_preview.png   | Bin 1171 -> 878 bytes
 3d_armor/textures/3d_armor_inv_boots_admin.png       | Bin 193 -> 129 bytes
 3d_armor/textures/3d_armor_inv_boots_bronze.png      | Bin 213 -> 129 bytes
 3d_armor/textures/3d_armor_inv_boots_cactus.png      | Bin 187 -> 129 bytes
 3d_armor/textures/3d_armor_inv_boots_diamond.png     | Bin 212 -> 129 bytes
 3d_armor/textures/3d_armor_inv_boots_gold.png        | Bin 182 -> 129 bytes
 3d_armor/textures/3d_armor_inv_boots_mithril.png     | Bin 203 -> 129 bytes
 3d_armor/textures/3d_armor_inv_boots_steel.png       | Bin 209 -> 129 bytes
 3d_armor/textures/3d_armor_inv_boots_wood.png        | Bin 213 -> 129 bytes
 3d_armor/textures/3d_armor_inv_chestplate_admin.png  | Bin 226 -> 142 bytes
 3d_armor/textures/3d_armor_inv_chestplate_bronze.png | Bin 246 -> 142 bytes
 3d_armor/textures/3d_armor_inv_chestplate_cactus.png | Bin 220 -> 142 bytes
 .../textures/3d_armor_inv_chestplate_diamond.png     | Bin 247 -> 142 bytes
 3d_armor/textures/3d_armor_inv_chestplate_gold.png   | Bin 215 -> 142 bytes
 .../textures/3d_armor_inv_chestplate_mithril.png     | Bin 242 -> 142 bytes
 3d_armor/textures/3d_armor_inv_chestplate_steel.png  | Bin 258 -> 142 bytes
 3d_armor/textures/3d_armor_inv_chestplate_wood.png   | Bin 244 -> 142 bytes
 3d_armor/textures/3d_armor_inv_helmet_admin.png      | Bin 218 -> 140 bytes
 3d_armor/textures/3d_armor_inv_helmet_bronze.png     | Bin 232 -> 140 bytes
 3d_armor/textures/3d_armor_inv_helmet_cactus.png     | Bin 212 -> 140 bytes
 3d_armor/textures/3d_armor_inv_helmet_diamond.png    | Bin 232 -> 140 bytes
 3d_armor/textures/3d_armor_inv_helmet_gold.png       | Bin 201 -> 140 bytes
 3d_armor/textures/3d_armor_inv_helmet_mithril.png    | Bin 228 -> 140 bytes
 3d_armor/textures/3d_armor_inv_helmet_steel.png      | Bin 229 -> 140 bytes
 3d_armor/textures/3d_armor_inv_helmet_wood.png       | Bin 232 -> 140 bytes
 3d_armor/textures/3d_armor_inv_leggings_admin.png    | Bin 222 -> 140 bytes
 3d_armor/textures/3d_armor_inv_leggings_bronze.png   | Bin 239 -> 155 bytes
 3d_armor/textures/3d_armor_inv_leggings_cactus.png   | Bin 214 -> 140 bytes
 3d_armor/textures/3d_armor_inv_leggings_diamond.png  | Bin 242 -> 155 bytes
 3d_armor/textures/3d_armor_inv_leggings_gold.png     | Bin 215 -> 155 bytes
 3d_armor/textures/3d_armor_inv_leggings_mithril.png  | Bin 237 -> 155 bytes
 3d_armor/textures/3d_armor_inv_leggings_steel.png    | Bin 234 -> 155 bytes
 3d_armor/textures/3d_armor_inv_leggings_wood.png     | Bin 237 -> 155 bytes
 3d_armor/textures/3d_armor_leggings_admin.png        | Bin 673 -> 351 bytes
 .../textures/3d_armor_leggings_admin_preview.png     | Bin 1940 -> 1340 bytes
 3d_armor/textures/3d_armor_leggings_bronze.png       | Bin 639 -> 335 bytes
 .../textures/3d_armor_leggings_bronze_preview.png    | Bin 1941 -> 1389 bytes
 3d_armor/textures/3d_armor_leggings_cactus.png       | Bin 695 -> 424 bytes
 .../textures/3d_armor_leggings_cactus_preview.png    | Bin 1885 -> 1340 bytes
 3d_armor/textures/3d_armor_leggings_diamond.png      | Bin 622 -> 306 bytes
 .../textures/3d_armor_leggings_diamond_preview.png   | Bin 1933 -> 1388 bytes
 3d_armor/textures/3d_armor_leggings_gold.png         | Bin 569 -> 298 bytes
 3d_armor/textures/3d_armor_leggings_gold_preview.png | Bin 1917 -> 1341 bytes
 3d_armor/textures/3d_armor_leggings_mithril.png      | Bin 760 -> 497 bytes
 .../textures/3d_armor_leggings_mithril_preview.png   | Bin 1917 -> 1380 bytes
 3d_armor/textures/3d_armor_leggings_steel.png        | Bin 578 -> 331 bytes
 .../textures/3d_armor_leggings_steel_preview.png     | Bin 1940 -> 1387 bytes
 3d_armor/textures/3d_armor_leggings_wood.png         | Bin 577 -> 285 bytes
 3d_armor/textures/3d_armor_leggings_wood_preview.png | Bin 1965 -> 1399 bytes
 3d_armor/textures/3d_armor_trans.png                 | Bin 146 -> 75 bytes
 3d_armor/textures/3d_armor_ui_form.png               | Bin 13356 -> 8332 bytes
 3d_armor/textures/character_preview.png              | Bin 1172 -> 907 bytes
 3d_armor/textures/inventory_plus_armor.png           | Bin 723 -> 544 bytes
 shields/textures/shields_inv_shield_admin.png        | Bin 580 -> 461 bytes
 shields/textures/shields_inv_shield_bronze.png       | Bin 654 -> 490 bytes
 shields/textures/shields_inv_shield_cactus.png       | Bin 419 -> 318 bytes
 shields/textures/shields_inv_shield_diamond.png      | Bin 640 -> 477 bytes
 .../textures/shields_inv_shield_enhanced_cactus.png  | Bin 476 -> 322 bytes
 .../textures/shields_inv_shield_enhanced_wood.png    | Bin 661 -> 583 bytes
 shields/textures/shields_inv_shield_gold.png         | Bin 610 -> 449 bytes
 shields/textures/shields_inv_shield_mithril.png      | Bin 647 -> 526 bytes
 shields/textures/shields_inv_shield_steel.png        | Bin 629 -> 546 bytes
 shields/textures/shields_inv_shield_wood.png         | Bin 600 -> 529 bytes
 shields/textures/shields_shield_admin.png            | Bin 543 -> 423 bytes
 shields/textures/shields_shield_admin_preview.png    | Bin 873 -> 609 bytes
 shields/textures/shields_shield_bronze.png           | Bin 683 -> 502 bytes
 shields/textures/shields_shield_bronze_preview.png   | Bin 1892 -> 1494 bytes
 shields/textures/shields_shield_cactus.png           | Bin 455 -> 325 bytes
 shields/textures/shields_shield_cactus_preview.png   | Bin 739 -> 536 bytes
 shields/textures/shields_shield_diamond.png          | Bin 668 -> 489 bytes
 shields/textures/shields_shield_diamond_preview.png  | Bin 1838 -> 1480 bytes
 shields/textures/shields_shield_enhanced_cactus.png  | Bin 515 -> 330 bytes
 .../shields_shield_enhanced_cactus_preview.png       | Bin 824 -> 530 bytes
 shields/textures/shields_shield_enhanced_wood.png    | Bin 693 -> 597 bytes
 .../shields_shield_enhanced_wood_preview.png         | Bin 1086 -> 787 bytes
 shields/textures/shields_shield_gold.png             | Bin 643 -> 462 bytes
 shields/textures/shields_shield_gold_preview.png     | Bin 1836 -> 1454 bytes
 shields/textures/shields_shield_mithril.png          | Bin 616 -> 489 bytes
 shields/textures/shields_shield_mithril_preview.png  | Bin 1796 -> 1480 bytes
 shields/textures/shields_shield_steel.png            | Bin 657 -> 561 bytes
 shields/textures/shields_shield_steel_preview.png    | Bin 1850 -> 1545 bytes
 shields/textures/shields_shield_wood.png             | Bin 626 -> 555 bytes
 shields/textures/shields_shield_wood_preview.png     | Bin 2126 -> 2055 bytes
```

**Pull request merged**
