### PR TITLE
remove /kill command

### PR DESCRIPTION
**Pull request by tenplus1**
remove /kill command since /killme does exactly the same function and is better named.

### CODE REVIEW

**Comment by stujones11** [comment]
/kill and /killme are not identical, the former requires the 'ban' privilege and kills a named player, while that player could be yourself that is not the intended use, see #62

**Comment by tenplus1** [comment]
True but the killing of any player other than yourself was never intended to be included in this mod, only a way to kill YOURSELF if stuck in a tricky position without harming your armor, so /kill should be removed and /killme kept for player usage.

**Comment by stujones11** [comment]
I realize that killing another player was not the original intention of the /kill command, that's why I added /killme. It did not make sense for it to take a parameter that it didn't even use. @paly2 changed it to give those with the 'ban' privilege the ability to kill players, it seemed reasonable enough to me, do you think there's problem with that?

Personally I am not sure either /kill or /killme belong in the mod but they do not bother me too much if other people want them. Since I did not add this feature myself I would rather get some other opinions before removing it.

**Comment by stujones11** [comment]
So they added /killme to MTG chat commands anyway, that is good. I will probably get rid of both of these commands on the next minetest version update unless there are any serious objections.

**Comment by Wuzzy2** [comment]
Yes, please remove this command, it does not belong in an armor mod IMO.
A kill command should be added in a different mod instead.
The problem with adding `kill` into this mod is also that it blocks the word “kill” for mods which want to add the `kill` command properly.

**Comment by Wuzzy2** [comment]
Closed? Huh? Now was this merged or not?

**Pull request closed without merging**
