### PR TITLE
Charecter model improvements - Extruded shield

### PR DESCRIPTION
**Pull request by ExeterDad**
-Added mesh so shield will appear extruded to be consistent with wielditem. I like!
-Pulled shield closer to hand so it doesn't appear to float.
-Scaled down slightly UV island for shield texture as bits of pixels of neighboring armor textures were glitching into shield mesh. Very noticeable once shields were extruded.
-Noticed two vertices of characters front left chin were included into Arm_Right vertex group. There was slight influence with arm movement. Likely a weight painting slip from the past. I cleared them from the group. 

Wish I would of completed before your latest release :/

Before:
screenshot_2808462798

After:
screenshot_2897036900

### CODE REVIEW

**Comment by stujones11** [comment]
Looks good! I will test and merge this asap, thanks once again for your great work.

**Comment by stujones11** [comment]
I made a bit of a mess of squashing and rebasing so ended up having to force push. You may need to re sync/clone your fork, sorry for any inconvenience.

**Comment by ExeterDad** [comment]
Heh heh! No worries. I might not of even noticed. I'm completely clueless using git.

**Comment by stujones11** [comment]
>Heh heh! No worries. I might not of even noticed. I'm completely clueless using git.

Me too, but i've leaned just enough to be a bit dangerous :/

One thing I might recommend for future PR's to this (or any other) repo would be to first create a 'feature branch', make/commit your changes and submit your PR from there. Once accepted/closed you can simply delete the feature branch without ever touching your master branch. This won't make any difference to the person merging/rebasing the request.

**Comment by ExeterDad** [comment]
Thanks for the tip! I'll make sure to remember that. Using they way I am now seems more trouble then it's worth :)

**Pull request closed without merging**
